### ISSUE TITLE
Installation fails with Node 13 (sharp package upgrade needed)

### ISSUE THREAD

**Issue by d4h0** [matyunya/svelte-image#37]
Hi,

Please upgrade the sharp package so it's possible to use your package with Node 13.

The [sharp package added support for Node 13 a while ago](https://github.com/lovell/sharp/commit/4009acdd303c3543271750259856ba6fc140f8b8).

**Comment by babycourageous** [comment]
@d4h0 I had some similar issues installing as well - would crap out when trying to build sharp. 

If it's any help i added a `resolutions` key to my package.json to get the install to finish: 

```
"resolutions": {
    "**/svelte-image/sharp": "0.23.4"
  }
```

This forces `svelte-image` to use the current version of `sharp` that supports Node 13 rather than the one listed in its dependencies.

**Comment by matyunya** [comment]
Should be fixed in 0.1.9.

**Comment by d4h0** [comment]
@babycourageous: Thanks for the tip

**Comment by babycourageous** [comment]
Thanks for the update @matyunya! 

@d4h0 you're welcome - hopefully ya didn't need it after the update!
